function ItemFilterModal(){var properties={multiSelectParticles:false,multiSelectQualities:false,multiSelectKillstreakers:false,multiSelectSheens:false,multiSelectKillstreakTiers:false,multiSelectStrangeParts:false,multiSelectPaints:false,enableNumericRanges:false,anySelectTradable:false,anySelectCraftable:false,anySelectAustralium:false,showItemPanel:false,showGeneralPanel:false,showQualityPanel:false,showParticlePanel:false,showPaintPanel:false,showNumericPanel:false,showKillstreakPanel:false,showKillstreakTierPanel:false,showSuggestionPanel:false,showClassifiedPanel:false,showStrangePartPanel:false,showSlotPanel:false,showClassPanel:false,hiddenFields:[],hint:null,modalTitle:null,loadingMessage:'<i class="fa fa-spinner fa-spin"></i> Loading filters...',source:null,addButtonText:"Confirm",cancelButtonText:"Cancel",preselectDefaultQuality:false,enableAdvancedItemFilters:false};var filters={sheens:null,killstreakers:null,killstreak_tiers:null,show_killstreak_tab:null,show_tradable:null,show_craftable:null,show_australium:null,default_quality:null,numerics:[],show_slot:null,show_class:null,strange_parts:null};var filtersLoaded=false;var advSearchTimeout;this.set=function(property,setting){properties[property]=setting;return this;};this.get=function(property){return properties[property];};this.getModal=function(callback){modal(properties.modalTitle,properties.loadingMessage);if(filtersLoaded){drawFilters(callback);}else{$.get('/pages/filter_meta',function(data){filters=data;filtersLoaded=true;drawFilters(callback);});}};var getMultiFilterList=function(){var res=[];if(properties.showQualityPanel){res.push("quality");}
if(properties.showPaintPanel){res.push("paint");}
if(properties.showParticlePanel){res.push("particle");}
if(properties.showStrangePartPanel){res.push("strange_parts");}
if(properties.showSuggestionPanel){res.push("state");}
if(properties.showKillstreakPanel){res.push("killstreaker");res.push("sheen");res.push("killstreak_tier");}
return res;};var drawFilters=function(callback){var modal=$('#active-modal');var body=modal.find('.modal-body');var buttons=modal.find('.modal-footer');body.html("");var panels=$('<div class="panel-group" id="filter-panels" />');if(properties.showItemPanel){var itemPanel=$('<div />');var itemSearch=$('<input type="text" id="adv-search-item-search" class="form-control" placeholder="Type an item name" />');var itemSearchResults=$('<div class="well well-sm" id="adv-search-item-search-results" />');var itemTypeFilter=$('<select id="filter-item-type" class="form-control" />');itemSearchResults.append($("<h5>Type something to begin.</h5>")).append($("<p class='text-muted'>Matching items will show up here.</p>"));itemPanel.append(itemSearch).append(itemSearchResults);if(properties.enableAdvancedItemFilters){itemTypeFilter.append($('<option value="item">Find listings containing this item</option>')).append($('<option value="target">Find recipes where the output item is used on this item</option>')).append($('<option value="output">Find recipes where this item is the output item</option>'));itemPanel.append(itemTypeFilter);}
panels.append(getPanel({body:itemPanel,title:'Item',id:'item',parent:'filter-panels',show:true}));}
if(properties.showGeneralPanel){var generalPanel=$('<div />');var generalRow=$('<div class="row filter-row" />');if(filters.show_tradable){if(properties.anySelectTradable){generalRow.append(getTrinaryFilter('tradable','Tradable',4));}else{generalRow.append(getBooleanFilter('tradable','Tradable',4,true));}}
if(filters.show_craftable){if(properties.anySelectCraftable){generalRow.append(getTrinaryFilter('craftable','Craftable',4));}else{generalRow.append(getBooleanFilter('craftable','Craftable',4,true));}}
if(filters.show_australium){if(properties.anySelectAustralium){generalRow.append(getTrinaryFilter('australium','Australium',4));}else{generalRow.append(getBooleanFilter('australium','Australium',4,false));}}
var appRow=$('<div class="row" />');generalPanel.append(generalRow);if(properties.showSlotPanel&&filters.show_slot){var checklist=$('<div id="filter-slot" />'),col=$('<div class="col-4" />');col.append($('<h5>Slot</h5>'));var slots={misc:'Cosmetic',melee:'Melee',primary:'Primary',secondary:'Secondary',pda:'PDA',action:'Action'};for(var slot in slots){checklist.append('<div class="checkbox"><label><input type="checkbox" name="'+ slot+'" /> '+ slots[slot]+'</label></div>');}
col.append(checklist);appRow.append(col);}
if(properties.showClassPanel&&filters.show_class){var checklist=$('<div id="filter-class" />'),col=$('<div class="col-4" />');col.append($('<h5>Class</h5>'));var classes={scout:'Scout',soldier:'Soldier',pyro:'Pyro',demoman:'Demoman',heavy:'Heavy',engineer:'Engineer',medic:'Medic',sniper:'Sniper',spy:'Spy'};for(var cls in classes){checklist.append('<div class="checkbox"><label><input type="checkbox" name="'+ cls+'" /> '+ classes[cls]+'</label></div>');}
col.append(checklist);appRow.append(col);}
generalPanel.append(appRow);panels.append(getPanel({body:generalPanel,title:'General',id:'general',parent:'filter-panels'}));}
if(properties.showQualityPanel&&filters.quality.length>0){panels.append(getPanel({body:getMultiFilter('filter-quality',filters.quality,null,!properties.multiSelectQualities),title:'Quality',id:'quality',parent:'filter-panels'}));}
if(properties.showPaintPanel&&filters.paint.length>0){panels.append(getPanel({body:getMultiFilter('filter-paint',filters.paint,'btn-xs',!properties.multiSelectPaints),title:'Paint',id:'paint',parent:'filter-panels'}));}
if(properties.showParticlePanel&&filters.particle.length>0){panels.append(getPanel({body:getMultiFilter('filter-particle',filters.particle,'btn-xs',!properties.multiSelectParticles),title:'Particle Effect',id:'particle',parent:'filter-panels'}));}
if(properties.showStrangePartPanel&&filters.strange_parts&&filters.strange_parts.length>0){panels.append(getPanel({body:getMultiFilter('filter-strange_parts',filters.strange_parts,'btn-xs',!properties.multiSelectStrangeParts),title:'Strange Parts',id:'strange_parts',parent:'filter-panels'}));}
if(properties.showKillstreakPanel&&filters.show_killstreak_tab){var killstreak_tab=$('<div />');if(properties.showKillstreakTierPanel){killstreak_tab.append($('<h5>Killstreak Tier</h5>')).append(getMultiFilter('filter-killstreak_tier',filters.killstreak_tiers,'btn-sm',!properties.multiSelectKillstreakTiers))}
killstreak_tab.append($('<h5 class="killstreak-filter-header">Sheen</h3>')).append(getMultiFilter('filter-sheen',filters.sheens,'btn-sm',!properties.multiSelectSheens)).append($('<h5 class="killstreak-filter-header">Killstreaker</h5>')).append(getMultiFilter('filter-killstreaker',filters.killstreakers,'btn-sm',!properties.multiSelectKillstreakers)).append($('<div id="killstreaker-warning" />'));panels.append(getPanel({body:killstreak_tab,title:'Killstreaker',id:'killstreak',parent:'filter-panels'}));}
if(properties.showNumericPanel){var row=$('<div class="row" />');var numeric_category_col=$('<div class="col-3" />');var numeric_category_select=$('<select class="form-control" id="filter-numeric-category" />');numeric_category_select.append($('<option value="none">(Select one)</option>'));for(var i=0;i<filters.numerics.length;i++){numeric_category_select.append($('<option value="'+ filters.numerics[i].field+'">'+ filters.numerics[i].name+'</option>'));}
numeric_category_col.append(numeric_category_select);row.append(numeric_category_col);var numeric_comparison_col=$('<div class="col-3" />');if(properties.enableNumericRanges){var numeric_comparison_select=$('<select class="form-control" id="filter-numeric-comparison" disabled />');numeric_comparison_select.append($('<option value="eq">equal to</option>')).append($('<option value="lt">less than</option>')).append($('<option value="gt">more than</option>')).append($('<option value="range">between</option>'));numeric_comparison_col.append(numeric_comparison_select);row.append(numeric_comparison_col);}
var numeric_value=$('<input type="text" class="form-control" disabled id="filter-numeric-value" />');var numeric_value_col=$('<div class="col-3" />');numeric_value_col.append(numeric_value);row.append(numeric_value_col);var numeric_value_high=$('<input type="text" style="display:none;" class="form-control" id="filter-numeric-value-high" placeholder="high" />');var numeric_value_high_col=$('<div class="col-3" />');numeric_value_high_col.append(numeric_value_high);row.append(numeric_value_high_col);panels.append(getPanel({body:row,title:'Numeric',id:'numeric',parent:'filter-panels'}));}
if(properties.showSuggestionPanel){var states=[{id:2,name:'Open'},{id:0,name:'Closed'},{id:1,name:'Accepted'}];var state_panel=$('<div />');var state_select=getMultiFilter('filter-state',states,'btn-sm',false);state_panel.append(state_select);panels.append(getPanel({body:state_panel,title:'Suggestion Status',id:'suggestion',parent:'filter-panels'}));var sort_panel=$('<div />');var sort_select=$('<select id="filter-sort" class="form-control" />');sort_select.append($('<option value="date">Sort by created date</option>')).append($('<option value="popular">Sort by popularity</option>'));var unvotable_checkbox=$('<div class="checkbox" />');unvotable_checkbox.append($('<label><input type="checkbox" id="filter-unvotable" /> Show suggestions I am unable to vote on</label>'));var unvoted_checkbox=$('<div class="checkbox" />');unvoted_checkbox.append($('<label><input type="checkbox" id="filter-unvoted" /> Only show suggestions I have not yet voted on</label>'));sort_panel.append(sort_select).append(unvoted_checkbox).append(unvotable_checkbox).append('<span class="help-block">Suggestions for highly valued items require a higher backpack value. These suggestions are hidden by default.</span>');panels.append(getPanel({body:sort_panel,title:'Sorting',id:'sorting',parent:'filter-panels'}));}
if(properties.showClassifiedPanel){var sort_panel=$('<div />');var sort_select=$('<select id="filter-sort" class="form-control" />');sort_select.append($('<option value="low">Sort by price, low-to-high</option>')).append($('<option value="high">Sort by price, high-to-low</option>')).append($('<option value="bump">Sort by bump time</option>'));var trade_offer_checkbox=$('<div class="checkbox" />');trade_offer_checkbox.append($('<label><input type="checkbox" id="filter-offers-only" /> Only show listings with Trade Offers</label>'));sort_panel.append(sort_select).append(trade_offer_checkbox);panels.append(getPanel({body:sort_panel,title:'Sorting',id:'sorting',parent:'filter-panels'}));}
body.append(panels);var searchBtn=$('<a class="btn btn-primary" id="confirm-">'+ properties.addButtonText+'</a>');buttons.html("");if(properties.hint){buttons.append($('<span class="text-muted modal-hint">'+ properties.hint+'</span>'));}
buttons.append(searchBtn).append($('<a class="btn btn-default" data-dismiss="modal">'+ properties.cancelButtonText+'</a>'));for(var index in properties.hiddenFields){body.append('<input type="hidden" id="filter-'+ properties.hiddenFields[index]+'" />');}
searchBtn.click(function(){callback(getParameters());});$('#filter-numeric-comparison').change(function(){updateNumericFilters();});$('#filter-numeric-category').change(function(){updateNumericFilters();});$('#filter-killstreak_tier').click(function(){setTimeout(checkConflictingFilters,100);});$('#filter-sheen').click(function(){setTimeout(checkConflictingFilters,100);});$('#filter-killstreaker').click(function(){setTimeout(checkConflictingFilters,100);});$('#adv-search-item-search').keyup(function(){clearTimeout(advSearchTimeout);advSearchTimeout=setTimeout(show_search_modal_suggestions,300);});$('#adv-search-item-search-results').on('click','.btn',function(){$('#adv-search-item-search').val($(this).text());});fillFilters();};var fillFilters=function(){var params=getSourceParameters();if(properties.preselectDefaultQuality&&!params.quality){$('#filter-quality').find('input[value="'+ filters.default_quality+'"]').click();}
if(properties.showGeneralPanel){if(params.tradable){$('#filter-tradable').val(params.tradable);}
if(params.craftable){$('#filter-craftable').val(params.craftable);}
if(params.australium){$('#filter-australium').val(params.australium);}
if(params.slot){var slots=params.slot.split(',');$('#filter-slot').children().each(function(){if(slots.indexOf($(this).find('input').attr('name'))!==-1){$(this).find('input').click();}});}
if(params.class){var classes=params.class.split(',');$('#filter-class').children().each(function(){if(classes.indexOf($(this).find('input').attr('name'))!==-1){$(this).find('input').click();}});}}
if(!params.state){$('#filter-state').find('[value="2"]').parent().click();}
var multiFilters=getMultiFilterList();for(var i=0;i<multiFilters.length;i++){var param=multiFilters[i];if(params[param]){var values=String(params[param]).split(',');$('#filter-'+ param).children().each(function(){if(values.indexOf($(this).children('input').val())!==-1){$(this).click();}});}}
if(params.item){$('#adv-search-item-search').val(params.item);}
if(params.item_type){$('#filter-item-type').val(params.item_type);}
if(params.sort){$('#filter-sort').val(params.sort);}
for(var index in properties.hiddenFields){var hiddenParam=properties.hiddenFields[index];if(params[hiddenParam]){$('#filter-'+ hiddenParam).val(params[hiddenParam]);}}
if(params.unvotable){$('#filter-unvotable').attr('checked','');}
if(params.unvoted){$('#filter-unvoted').attr('checked','');}
if(params.offers){$('#filter-offers-only').attr('checked','');}
if(properties.showNumericPanel&&params.numeric&&params.numeric!='none'){$('#filter-numeric-category').val(params.numeric);$('#filter-numeric-comparison').val(params.comparison);if(params.comparison=='range'){$('#filter-numeric-value').val(params.low);$('#filter-numeric-value-high').val(params.high);}else{$('#filter-numeric-value').val(params.value);}
updateNumericFilters();}};var getSourceParameters=function(){if(properties.source){return getElementParameters();}else{return getSearchParameters();}};var getElementParameters=function(){return properties.source.data();};var getSearchParameters=function(){var prmstr=window.location.search.substr(1);return prmstr!=null&&prmstr!=""?transformToAssocArray(prmstr):{};};var transformToAssocArray=function(prmstr){var params={};var prmarr=prmstr.split("&");for(var i=0;i<prmarr.length;i++){var tmparr=prmarr[i].split("=");params[tmparr[0]]=decodeURI(tmparr[1]);}
return params;};var getPanel=function(options){options.id='panel-'+ options.id;var panel=$('<div class="panel panel-filter" />');var heading=$('<div class="panel-heading" />');var title=$('<a data-toggle="collapse" data-parent="#'+ options.parent+'" href="#'+ options.id+'" class="panel-title">'+ options.title+'</a>');heading.append(title);var collapsible=$('<div id="'+ options.id+'" class="panel-collapse collapse'+(options.show!==undefined?' in':'')+'" />');var body=$('<div class="panel-body" />');body.append(options.body);collapsible.append(body);panel.append(heading);panel.append(collapsible);return panel;};var getTrinaryFilter=function(field,name,col_size){var select=$('<select id="filter-'+ field+'" class="form-control" />'),col=$('<div class="col-'+ col_size+'" />');select.append($('<option value="0">'+ name+': Any</option>')).append($('<option value="1">'+ name+': Yes</option>')).append($('<option value="-1">'+ name+': No</option>'));col.append(select);return col;};var getBooleanFilter=function(field,name,col_size,on){var select=$('<select id="filter-'+ field+'" class="form-control" />'),col=$('<div class="col-'+ col_size+'" />');var state=false;if(on!==undefined&&on){state=true;}
select.append($('<option value="1">'+ name+': Yes</option>')).append($('<option value="0"'+(state?'':' selected')+'>'+ name+': No</option>'));col.append(select);return col;};var getMultiFilter=function(element_id,data_list,button_class,singular){var input_type='checkbox';if(button_class===undefined){button_class='btn-sm';}
if(singular!==undefined&&singular){input_type='radio';}
var res=$('<div />');var group_buttons=$('<span id="'+ element_id+'" class="btn-list" data-toggle="buttons" />');for(var i=0;i<data_list.length;i++){var button=$('<label class="btn btn-default '+ button_class+'" />');button.append($('<input type="'+ input_type+'" value="'+ data_list[i].id+'"/>'));if(data_list[i].color){button.append($('<i class="fa fa-circle fa-fw" style="color:#'+ data_list[i].color+'"></i>'));}
button.append(data_list[i].name);group_buttons.append(button);}
res.append(group_buttons);if(input_type=='radio'){var reset_btn=$('<a class="btn btn-danger btn-reset '+ button_class+'">Reset</a>');reset_btn.click(function(){group_buttons.children().removeClass('active');});res.append(reset_btn);}
return res;};var getParameters=function(){var params={};if(properties.showGeneralPanel){var tradable=$('#filter-tradable');if(tradable.length&&tradable.val()!=0){params.tradable=tradable.val();}
var craftable=$('#filter-craftable');if(craftable.length&&craftable.val()!=0){params.craftable=craftable.val();}
var australium=$('#filter-australium');if(australium.length&&australium.val()!=0){params.australium=australium.val();}
var classes=[];$('#filter-class').children().each(function(){var checkbox=$(this).find('[type="checkbox"]');if(checkbox.is(':checked')){classes.push(checkbox.attr('name'));}});if(classes.length>0){params.class=classes.join(',');}
var slots=[];$('#filter-slot').children().each(function(){var checkbox=$(this).find('[type="checkbox"]');if(checkbox.is(':checked')){slots.push(checkbox.attr('name'));}});if(slots.length>0){params.slot=slots.join(',');}}
if(properties.showItemPanel){if($('#adv-search-item-search').val()!=""){params.item=$('#adv-search-item-search').val();}
if($('#filter-item-type').val()!='item'){params.item_type=$('#filter-item-type').val();}}
var multiFilters=getMultiFilterList();for(var i=0;i<multiFilters.length;i++){var param=multiFilters[i];var values=[];$('#filter-'+ param).children().each(function(){if($(this).hasClass('active')){values.push($(this).children().val());}});if(values.length>0){params[param]=values.join(',');}}
if(properties.showSuggestionPanel){if(params.state&&params.state=="2"){delete(params.state);}
if($('#filter-unvotable').is(':checked')){params.unvotable=1;}
if($('#filter-unvoted').is(':checked')){params.unvoted=1;}}
if(properties.showNumericPanel){var numeric_category=$('#filter-numeric-category');if(numeric_category.length&&numeric_category.val()!='none'){params.numeric=numeric_category.val();params.comparison=$('#filter-numeric-comparison').val();if(params.comparison=='range'){params.low=$('#filter-numeric-value').val();params.high=$('#filter-numeric-value-high').val();}else{params.value=$('#filter-numeric-value').val();}}}
for(var index in properties.hiddenFields){var param=properties.hiddenFields[index];if($('#filter-'+ param).val()!=""){params[param]=$('#filter-'+ param).val();}}
if(properties.showClassifiedPanel){if($('#filter-offers-only').is(':checked')){params.offers=1;}
var sort=$('#filter-sort').val();if(sort=='low'){if(Object.keys(params).length==0){params.sort=sort;}}else{if(!(Object.keys(params).length==0&&sort=='bump')){params.sort=sort;}}}
if(properties.showSuggestionPanel){var sort=$('#filter-sort').val();if(sort=='popular'){params.sort=sort;}}
return params;};var checkConflictingFilters=function(){var params=getParameters();$('#killstreaker-warning').html("");if(params.killstreak_tier){params.killstreak_tier=params.killstreak_tier.split(',');if(params.killstreaker){if(params.killstreak_tier.indexOf("0")!==-1||params.killstreak_tier.indexOf("1")!==-1||params.killstreak_tier.indexOf("2")!==-1){$('#killstreaker-warning').html($('<div class="alert alert-warning"><i class="fa fa-warning"></i> You have selected contradicting filters. Killstreakers can only exist on Professional Killstreak items.</div>'));}}
if(params.sheen){if(params.killstreak_tier.indexOf("0")!==-1||params.killstreak_tier.indexOf("1")!==-1){$('#killstreaker-warning').html($('<div class="alert alert-warning"><i class="fa fa-warning"></i> You have selected contradicting filters. Sheens can only exist on Specialized and Professional Killstreak items.</div>'));}}}};var updateNumericFilters=function(){if($('#filter-numeric-comparison').val()=='range'){$('#filter-numeric-value').attr('placeholder','low');$('#filter-numeric-value-high').show();}else{$('#filter-numeric-value').removeAttr('placeholder');$('#filter-numeric-value-high').hide();}
if($('#filter-numeric-category').val()=='none'){$('#filter-numeric-comparison').attr('disabled','');$('#filter-numeric-value').attr('disabled','');$('#filter-numeric-value-high').attr('disabled','');}else{$('#filter-numeric-comparison').removeAttr('disabled');$('#filter-numeric-value').removeAttr('disabled');$('#filter-numeric-value-high').removeAttr('disabled');}}}